export const TOGGLE_PRODUCT = "TOGGLE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_ALL_PRODUCTS = "DELETE_ALL_PRODUCTS";
export const CONFIRM_ORDER = "CONFIRM_ORDER";
export const DELETE_ORDER_HISTORY = "DELETE_ORDER_HISTORY";
export const GET_COUNTER = "GET_COUNTER";
